export const AUTO_REMEDIABLE = [
  "S3_001", "S3_BLOCK_PUBLIC_ACCESS",
  "S3_002", "S3_DEFAULT_ENCRYPTION_DISABLED", "S3_DEFAULT_ENCRYPTION_NOT_KMS",
  "S3_003", "S3_VERSIONING_DISABLED",
  "IAM_001", "IAM_WEAK_PASSWORD_POLICY", "IAM_NO_PASSWORD_POLICY",
  "IAM_002", "IAM_ACCESS_KEY_ROTATION_REQUIRED",
  "EC2_001", "EC2_SSH_PUBLIC",
  "EC2_002", "EC2_RDP_PUBLIC",
  "EC2_003", "EC2_IMDSV2_NOT_ENFORCED"
];

export const MANUAL_ONLY = [
  "IAM_003", "IAM_ROOT_ACCESS_KEYS"
];
